openapi: 3.0.0
servers:
- url: https://app-test-ws.star-app.ch
  description: ''
- url: https://app-prod-ws.star-app.ch
  description: ''
info:
  version: 1.0-develop
  description: STARSDK API
  title: STARSDK API
paths:
  /v1/:
    get:
      summary: hello
      description: hello
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/exposed:
    post:
      summary: addExposee
      description: Enpoint used to publish the secretkey.
      responses:
        '200':
          description: Returns OK if successfull
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Either key is not base64 or no auth data given
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ch.ubique.starsdk.model.ExposeeRequest'
        description: N/A
      parameters:
      - name: User-Agent
        in: header
        description: ''
        required: true
        schema:
          type: string
  /v1/exposed/{dayDateStr}:
    get:
      summary: getExposed
      description: ''
      responses:
        '200':
          description: Returns ExposedOverview, which includes all secretkeys which
            were published on dayDateStr.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ch.ubique.starsdk.model.ExposedOverview'
        '500':
          description: If the date time string is not parseable.
      parameters:
      - name: dayDateStr
        in: path
        description: ''
        required: true
        schema:
          type: string
components:
  schemas:
    ch.ubique.starsdk.model.AuthDataMethod:
      type: string
      enum:
      - NONE
      - REDEEM_CODE
    ch.ubique.starsdk.model.ExposedOverview:
      type: object
      properties:
        exposed:
          type: array
          items:
            $ref: '#/components/schemas/ch.ubique.starsdk.model.Exposee'
          description: A list of all SecretKeys
          example: ''
    ch.ubique.starsdk.model.Exposee:
      type: object
      required:
      - key
      properties:
        Id:
          type: integer
        key:
          type: string
          description: The SecretKey of a exposed.
          example: AAAA
    ch.ubique.starsdk.model.ExposeeAuthData:
      type: object
      properties:
        value:
          type: string
          description: Authentication data used to verify the test result
          example: ''
        method:
          $ref: '#/components/schemas/ch.ubique.starsdk.model.AuthDataMethod'
          description: Specify the method, which should be used to verify data
          example: ''
    ch.ubique.starsdk.model.ExposeeRequest:
      type: object
      required:
      - key
      - authData
      properties:
        key:
          type: string
          description: The SecretKey used to generate EphID
          example: ''
        authData:
          $ref: '#/components/schemas/ch.ubique.starsdk.model.ExposeeAuthData'
          description: AuthenticationData provided by the health institutes to verify
            the test results
          example: ''
